- package-lock.json
- package.json
- src/popup/components/signTx.vue
- src/popup/index.js
- src/popup/root.vue
- src/utils/key_storage.js
- src/utils/sign.js
- test/keyStorage.test.js
- test/sign.test.js
- test/signTx.test.js
> View for signing transaction [ch357]

- src/backend/index.js
- src/manifest.js
- src/popup/components/transactionDetails.vue
- test/transactionDetails.test.js
> Extract details from Bitcoin transaction [ch1190]

- package.json
- src/manifest.json
- src/popup/components/firstRun.vue
- src/popup/root.vue
Changed to version 0.0.5.
small UI changes
removed hamburger menu being displayed on First Run.
> version changes

- package.json
- src/svelte/IDE/IdeMethodTx.svelte
- src/svelte/IDE/IdeMethods.svelte
- src/svelte/IDE/IdeSubmitContract.svelte
- src/svelte/coins/CoinConfirmTx.svelte
- src/svelte/components/DropDown.svelte
- src/svelte/misc/Transaction.svelte
> Fixed point fix

- README.md
- package-lock.json
- package.json
- src/js/background.js
- src/js/stores/filesStore.js
- src/js/stores/settingsStore.js
- src/svelte/IDE/IdeGetVariable.svelte
- src/svelte/IDE/IdeMain.svelte
- src/svelte/IDE/IdeModelNewTab.svelte
- src/svelte/coins/CoinSendingTx.svelte
- src/svelte/components/Card.svelte
- src/svelte/components/TxInfoBox.svelte
- src/svelte/devtools/DevToolsNetworks.svelte
IDE
- New tab button can how open blank contracts
- better formatting/layout of tab
- submitting tx/contract now waits for second tx result before displaying final result box.
> Ide modifications/testing

- README.md
- src/js/background.js
- src/js/stores/dappStore.js
- src/js/stores/settingsStore.js
- src/js/stores/stores.js
- src/svelte/coins/CoinOptions.svelte
New Feature:
The ability to assign an approved dApp to another keypair. To do this click on the keypair you want to assign the dapp to, goto Options, then choose the dApp from the dropdown list. Click "okay" to confirm.
All tests passing
> Reassign dapp

- README.md
- package.json
- src/js/stores/networksStore.js
- src/svelte/components/Step.svelte
- src/svelte/swaps/SwapsMain.svelte
- src/svelte/swaps/SwapsSendApproval.svelte
- src/svelte/swaps/SwapsSendEthTx.svelte
> Google translator fix

- README.md
- package.json
- selenium/fixtures/dappsInfo.json
- selenium/helpers/helpers.js
- selenium/tests/dapp/content_lamdenWalletConnect.js
- src/js/backgroundControllers/dappController.js
- src/js/backgroundControllers/masterController.js
- src/js/backgroundControllers/messagesHandler.js
- src/js/utils.js
- src/svelte/IDE/IdeGetVariable.svelte
- src/svelte/coins/Coin.svelte
- src/svelte/coins/CoinDappTrusted.svelte
- src/svelte/components/Charm.svelte
- src/svelte/confirms/ApproveConnection.svelte
- src/svelte/confirms/ApproveConnectionFund.svelte
- src/svelte/confirms/ApproveConnectionTrusted.svelte
- src/svelte/confirms/CurrencyApproval.svelte
- src/svelte/confirms/ReApproveConnection.svelte
Added the ability for a dapp to update its connection data using a versioning system. 
Smart Contracts can be updated but they will require popup approval by the user.  
Minor graphical tweaks and __fixed__ objects now display in charms.
> DAPP integration fixes and features

- README.md
- package.json
- selenium/config/config.js
- src/js/stores/filesStore.js
- src/js/utils.js
- src/svelte/coins/Coin.svelte
- src/svelte/coins/CoinModify.svelte
- src/svelte/components/Charm.svelte
- src/svelte/components/InputBox.svelte
- src/svelte/confirms/ApproveTransaction.svelte
- src/svelte/swaps/SwapsDisclaimer_ExchangeTerms.svelte
- src/svelte/swaps/SwapsDisclaimer_Questions.svelte
- src/svelte/swaps/SwapsDisclaimer_TokensExchange.svelte
fixes:
- remove trailing zeros from charm values
- balances cache refresh when account is deleted
- new contract name in ide changed to "con_new_contact"
- potential resize textarea bug fix for token swap
> Minor fixes

- src/js/utils.js
- src/svelte/IDE/IdeMain.svelte
- src/svelte/components/DatePicker.svelte
> fixed datepicker providing incorrect date on manual update

- README.md
- package-lock.json
- package.json
- src/js/backgroundControllers/accountsController.js
- src/js/backgroundControllers/masterController.js
- src/js/backgroundControllers/transactionsController.js
- src/js/utils.js
- src/svelte/IDE/IdeGetVariable.svelte
- src/svelte/IDE/IdeMain.svelte
- src/svelte/IDE/IdeMethods.svelte
- src/svelte/components/DatePicker.svelte
- Updated to latest version of lamden-js to allow DateTime and TimeDelta to be sent as objects instead of arrays.
> Date picker fix

- README.md
- package.json
- src/svelte/coins/CoinAddAccount.svelte
- src/svelte/coins/CoinAddDetails.svelte
- src/svelte/components/ResultBox.svelte
Fixes
- Broke adding accounts with token integration upgrade. That now works again.
> fixed adding accounts

- package.json
- selenium/config/config.js
- selenium/fixtures/swapInfo.json
- selenium/tests/crypto/clearingHouse_API.js
- selenium/tests/crypto/ethereum.js
- src/js/backgroundControllers/masterController.js
- src/js/backgroundControllers/messagesHandler.js
- src/js/backgroundControllers/networkController.js.js
- src/js/backgroundControllers/transactionsController.js
- src/js/crypto/ethereum.js
- src/js/stores/swapsStore.js
- src/js/utils.js
- src/svelte/Router.svelte
- src/svelte/swaps/SwapsCheckStatus.svelte
- src/svelte/swaps/SwapsChooseLamden.svelte
- src/svelte/swaps/SwapsConnectMetamask.svelte
- src/svelte/swaps/SwapsDisclaimer_ExchangeTerms.svelte
- src/svelte/swaps/SwapsMain.svelte
- src/svelte/swaps/SwapsRecover.svelte
- src/svelte/swaps/SwapsSendApproval.svelte
- src/svelte/swaps/SwapsSendEthTx.svelte
All tests passing:
- Token Swap better at recovering from errors.
- Added the ability to recover from a failed swap
> Fix swap process

- selenium/helpers/helpers-token.js
- selenium/tests/dapp/content_lamdenWalletSendTx.js
- selenium/tests/ui/tokens/tokens-add.js
- src/js/stores/coinStore.js
- src/svelte/coins/CoinAddToken.svelte
- src/svelte/coins/CoinLamdenContract.svelte
- src/svelte/coins/CoinLamdenSimpleContract.svelte
- src/svelte/coins/CoinsMain.svelte
- src/svelte/confirms/ApproveConnectionAccount.svelte
- src/svelte/connections/ConnectionOption.svelte
- Fix wallet allowing Dapps to connect to watched accounts
- Separate out watched accounts from real accounts on accounts screen.
- Filter out watched accounts from "Send" dropdown boxes
> Hotfix 1.8.6

- src/js/backgroundControllers/accountsController.js
- src/svelte/coins/CoinsMain.svelte
- src/svelte/components/Identicons.svelte
> new features

- README.md
Small fixes for spelling/capitalization
> Fixing spelling/capitalization in README.md

- package.json
- src/js/backgroundControllers/dappController.js
- src/js/services/fauna.js
- src/svelte/App.svelte
- src/svelte/coins/Coin.svelte
- src/svelte/coins/CoinEmpty.svelte
- src/svelte/misc/News.svelte
- src/svelte/tokens/TokenDetails.svelte
- fixes what's new sections
- hides zero token balances
> Hotfix 2.0.1

- selenium/tests/ui/coin/coin-btn.js
- src/js/backgroundControllers/networkController.js
- src/svelte/coins/CoinDetails.svelte
- src/svelte/coins/CoinLamdenReceive.svelte
- src/svelte/coins/CoinLamdenSimpleContract.svelte
- src/svelte/components/ResultBox.svelte
- src/svelte/confirms/CurrencyApproval.svelte
- src/svelte/connections/Connection.svelte
- src/svelte/connections/ConnectionDetails.svelte
- whitelabel.json
1.  fix currency symbol issues.
2.  fix block explorer issues.
> fix issues

- package.json
- selenium/tests/ui/coin/coin-btn.js
- src/js/backgroundControllers/networkController.js
- src/svelte/coins/CoinDetails.svelte
- src/svelte/coins/CoinLamdenReceive.svelte
- src/svelte/coins/CoinLamdenSimpleContract.svelte
- src/svelte/components/ResultBox.svelte
- src/svelte/confirms/CurrencyApproval.svelte
- src/svelte/connections/Connection.svelte
- src/svelte/connections/ConnectionDetails.svelte
- whitelabel.json
> Hotfix 2.1.5

- package.json
- selenium/tests/dapp/content_lamdenWalletSendTx.js
- src/svelte/confirms/CurrencyApproval.svelte
- Fixed blank popup for currency (TAU) approvals.
All tests passed.
> Hotfix 2.1.6

- selenium/tests/ui/misc/fiat.js
- selenium/tests/ui/tokens/tokens-edit.js
- src/js/backgroundControllers/transactionsController.js
- src/svelte/App.svelte
- src/svelte/IDE/IdeMain.svelte
- src/svelte/IDE/IdeMonacoEditor.svelte
- src/svelte/coins/Coin.svelte
- src/svelte/coins/CoinsMain.svelte
- src/svelte/connections/ConnectionsMain.svelte
- src/svelte/layouts/LeftSideFullPage.svelte
- src/svelte/menu/Menu.svelte
- src/svelte/menu/MenuBox.svelte
- src/svelte/menu/MenuItem.svelte
- src/svelte/nav/Nav.svelte
- src/svelte/nav/NavControls.svelte
- src/svelte/nav/NavForApp.svelte
- src/svelte/nav/NavLogo.svelte
- src/svelte/tokens/TokenDetails.svelte
1. Improve Responsive UI
2. Fix logout failed issue
3. Fix the issue that sometimes block service return nothing for transaction and then the wallet throw error.
4. New test cases
> much updates

- package-lock.json
- package.json
- selenium/config/chrome_config.json
- selenium/config/config.js
- selenium/fixtures/dappsInfo_v2.json
- selenium/helpers/helpers.js
- selenium/tests/dapp/content_lamdenWalletConnect_v2.js
- selenium/tests/dapp/content_lamdenWalletGetInfo_v2.js
- selenium/tests/dapp/content_lamdenWalletSendTx_v2.js
- selenium/tests/dapp/content_landenWalletSendTxBacktoBack_v2.js
- selenium/tests/ui/misc/network.js
- src/js/backgroundControllers/dappController.js
- src/js/backgroundControllers/masterController.js
- src/js/backgroundControllers/messagesHandler.js
- src/js/backgroundControllers/networkController.js
- src/svelte/coins/Coin.svelte
- src/svelte/coins/CoinDappSettings.svelte
- src/svelte/coins/CoinDappTrusted.svelte
- src/svelte/components/Charms.svelte
- src/svelte/components/DropDown.svelte
- src/svelte/confirms/ReApproveConnection.svelte
- src/svelte/connections/ConnectionDetails.svelte
- src/svelte/connections/ConnectionTrusted.svelte
- src/svelte/connections/ConnectionsMain.svelte
- whitelabel.json
Fix the issue that wallet is seting V2 transactions with timestamp
> set network version
